export const plans = [
    {
        title: "Basic",
        bookCount: "1",
        price: "399",
        backgroundColor: "#FFE6E3",
        borderColor: "#F75549",
        image: "/images/Art/plan-1.png",
        planId: 1,
        razorpayId: "plan_Kfp8XM8HNym5or",
        savings: '500',
    },
    {
        title: "Standard",
        bookCount: "2",
        price: "599",
        actualPrice: "799",
        backgroundColor: "#F0FEDF",
        borderColor: "#33A200",
        image: "/images/Art/plan-2.png",
        planId: 2,
        razorpayId: "plan_KfpBDN0ZyGY29s",
        savings: '750',
    },
    {
        title: "Premium",
        bookCount: "4",
        price: "799",
        actualPrice: "1199",
        backgroundColor: "#DEF2FF",
        borderColor: "#1596DC",
        image: "/images/Art/plan-3.png",
        planId: 3,
        razorpayId: "plan_KfpCxeWR1J5CkD",
        savings: '1000',
    },
];
