export const bookArchives = [
	{
		title: 'Current Books',
		emptyText: <div><h1>No Books</h1><h3>Borrowed yet</h3></div>,
		emptyImage: '/icons/current-books.png',
		name: 'currentBooks',
		overlay: 'current',
	},
	{
		title: 'Rate Previous Books',
		emptyText: <div><h1>No Books</h1><h3>to rate right now</h3></div>,
		emptyImage: '/icons/rate-previous-books.png',
		name: 'previousBooks',
		overlay: 'previous',
	},
	{
		title: 'Book Dump',
		emptyText: <div><h3>Book Dump</h3><h1>is Empty</h1></div>,
		emptyImage: '/icons/book-dump.png',
		name: 'dumpedBooks',
		overlay: 'dump',
	},
];

export const suggestedCategories = [
	{
		name: 'Beatrix Potter',
		image: '/images/Authors/Beatrix Potter.jpg',
	},
	{
		name: 'Penguin',
		image: './images/Publishers/Penguin.png',
	},
	{
		name: 'Charlie and Lola',
		image: '/images/Series/Charlie and Lola.jpg',
	},
	{
		name: 'First Readers',
		image: './images/Type of Books/First Readers.png',
	},
	{
		name: 'Bill Bryson',
		image: '/images/Authors/Bill Bryson.jpg',
	},
	{
		name: 'Puffin',
		image: './images/Publishers/Puffin.png',
	},
	{
		name: 'Clarice Bean',
		image: '/images/Series/Clarice Bean.jpg',
	},
	{
		name: 'Early Learners',
		image: './images/Type of Books/Early Learners.png',
	},
	{
		name: 'C. S. Lewis',
		image: '/images/Authors/C. S. Lewis.jpg',
	},
	{
		name: 'Scholastic',
		image: './images/Publishers/Scholastic.png',
	},
	{
		name: 'Diary of a Wimpy Kid',
		image: '/images/Series/Diary of a Wimpy Kid.jpg',
	},
	{
		name: 'Novel',
		image: './images/Type of Books/Novel.png',
	},
];

export const sampleBooks = [
	{
		name: 'The Fairytale Hairdresser and Aladdin',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/5525/9780552575195.jpg',
		isbn13: 9780552575195,
		age_group: '3-5',
		series: 'The Fairytale Hairdresser',
		authors: [ 'Abie Longstaff' ],
		illustrator: 'Lauren Beard',
		publication: 'Penguin',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Princess and Fairies' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'The Fairytale Hairdresser and Rapunzel',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/5525/9780552561860.jpg',
		isbn13: 9780552561860,
		age_group: '3-5',
		series: 'The Fairytale Hairdresser',
		authors: [ 'Abie Longstaff' ],
		illustrator: 'Lauren Beard',
		publication: 'Penguin',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Princess and Fairies' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'The Fairytale Hairdresser and the Princess and the Frog',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1413/9780141386645.jpg',
		isbn13: 9780141386645,
		age_group: '3-5',
		series: 'The Fairytale Hairdresser',
		authors: [ 'Abie Longstaff' ],
		illustrator: 'Lauren Beard',
		publication: 'Penguin',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Princess and Fairies' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'The Fairytale Hairdresser and the Princess and the Pea',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/5525/9780552575188.jpg',
		isbn13: 9780552575188,
		age_group: '3-5',
		series: 'The Fairytale Hairdresser',
		authors: [ 'Abie Longstaff' ],
		illustrator: 'Lauren Beard',
		publication: 'Penguin',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Princess and Fairies' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'Superhero Hotel',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4071/9781407166902.jpg',
		isbn13: 9781407166902,
		age_group: '3-5',
		series: '',
		authors: [ 'Abie Longstaff' ],
		illustrator: 'Migy Blanco',
		publication: 'Scholastic',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Superheroes and Pirates' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'Get Freddie Ready for the Monster Ball',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/9108/9781910851227.jpg',
		isbn13: 9781910851227,
		age_group: '3-5',
		series: '',
		authors: [ 'Adam Bestwick' ],
		illustrator: 'Claire Evans',
		publication: 'Fourth Wall Publishing',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Dinosaurs and Dragons' ],
		type_of_book: 'Flip Flap',
	},
	{
		name: 'Beast Quest: Rashouk the Cave Troll : Series 4 Book 3',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4083/9781408303788.jpg',
		isbn13: 9781408303788,
		age_group: '9-11',
		series: 'Beast Quest',
		authors: [ 'Adam Blade' ],
		illustrator: '',
		publication: "Hachette Children's Group",
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Historical Fiction', 'Fantasy Fiction' ],
		type_of_book: 'Novel',
	},
	{
		name: 'Beast Quest: Skor the Winged Stallion : Series 3 Book 2',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/8461/9781846169984.jpg',
		isbn13: 9781846169984,
		age_group: '9-11',
		series: 'Beast Quest',
		authors: [ 'Adam Blade' ],
		illustrator: '',
		publication: "Hachette Children's Group",
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Historical Fiction', 'Fantasy Fiction' ],
		type_of_book: 'Novel',
	},
	{
		name: 'Beast Quest: Stealth the Ghost Panther : Series 4 Book 6',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4083/9781408303801.jpg',
		isbn13: 9781408303801,
		age_group: '9-11',
		series: 'Beast Quest',
		authors: [ 'Adam Blade' ],
		illustrator: '',
		publication: "Hachette Children's Group",
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Historical Fiction', 'Fantasy Fiction' ],
		type_of_book: 'Novel',
	},
	{
		name: 'Beast Quest: Trema the Earth Lord : Series 5 Book 5',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4083/9781408304419.jpg',
		isbn13: 9781408304419,
		age_group: '9-11',
		series: 'Beast Quest',
		authors: [ 'Adam Blade' ],
		illustrator: '',
		publication: "Hachette Children's Group",
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Historical Fiction', 'Fantasy Fiction' ],
		type_of_book: 'Novel',
	},
	{
		name: 'Little Miss Trouble and the Mermaid',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4052/9781405292382.jpg',
		isbn13: 9781405292382,
		age_group: '6-8',
		series: '',
		authors: [ 'Adam Hargreaves', 'Roger Hargreaves' ],
		illustrator: '',
		publication: 'Egmont UK Ltd',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Princess and Fairies', 'Animals' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'Mr Impossible and the Easter Egg Hunt',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4052/9781405288828.jpg',
		isbn13: 9781405288828,
		age_group: '6-8',
		series: '',
		authors: [ 'Adam Hargreaves', 'Roger Hargreaves' ],
		illustrator: '',
		publication: 'Egmont UK Ltd',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Festivals', 'Cartoons' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'Busy Santa',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4472/9781447285465.jpg',
		isbn13: 9781447285465,
		age_group: '0-2',
		series: '',
		authors: [ 'Ag Jatkowska' ],
		illustrator: '',
		publication: 'MacMillan',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Festivals' ],
		type_of_book: 'Flip Flap',
	},
	{
		name: 'The Last Seance : Tales of the Supernatural by Agatha Christie',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0083/9780008336738.jpg',
		isbn13: 9780008336738,
		age_group: '12-14',
		series: '',
		authors: [ 'Agatha Christie' ],
		illustrator: '',
		publication: 'HarperCollins Publishers',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Mystery', 'Horror' ],
		type_of_book: 'Novel',
	},
	{
		name: 'Unfortunately',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4083/9781408311257.jpg',
		isbn13: 9781408311257,
		age_group: '3-5',
		series: '',
		authors: [ 'Alan Durant' ],
		illustrator: 'Simon Rickerty',
		publication: "Hachette Children's Group",
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Animals' ],
		type_of_book: 'Illustrations',
	},
	{
		name: 'Horror!',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/8471/9781847154613.jpg',
		isbn13: 9781847154613,
		age_group: '9-11',
		series: 'Dirty Birtie',
		authors: [ 'Alan MacDonald' ],
		illustrator: 'David Roberts',
		publication: 'Little Tiger Press Group',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Young Adult Fiction', 'Humor' ],
		type_of_book: 'Novel',
	},
	{
		name: '1001 Things to Spot at Christmas',
		image: 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/7460/9780746097939.jpg',
		isbn13: 9780746097939,
		age_group: '3-5',
		series: '',
		authors: [ 'Alex Frith' ],
		illustrator: 'Teri Gower',
		publication: 'Usborne',
		most_borrowed: false,
		amazon_best_seller: false,
		tags: [ 'Festivals' ],
		type_of_book: 'Activity',
	},
];
